### ISSUE TITLE
Issue with Final Trajectory Bird's-Eye Visualization

### ISSUE THREAD

**Issue by aitorarrietamarcos** [mathworks/vehicle-pure-pursuit#1]
Hi, in the purePursuitUSCity model, the Final Trajectory Bird's-Eye visualization gives me an error.

First, there was an error that the Aerospace blockset (and therefore Aerospace toolbox) was required. I suggest including this in the readme.md file.

After this, I have an error with the packEgo function, referring to an unrecognize variable (BusActorsActors)

![Captura](https://user-images.githubusercontent.com/24584925/92585409-33b88100-f295-11ea-8947-1fd82598fd25.PNG)

**Comment by veeralakshendra** [comment]
Hi Aitor,

Thanks for your feedback. I have added the Aerospace Blockset and Aerospace Toolbox in the README.md file. Please note that the Aerospace Blockset and Aerospace Toolbox are only required for the "purePursuitUSCity" model to convert from rad/s to degree/s. In case of the absence of these two toolboxes, define the conversion factor from rad/s to degree/s using a gain block and use the model.

Regarding the packEgo function error, as mentioned by Mustafa, there was an issue with the Scenario Reader block. The scenario scene was located in my local folder. I have fixed the issue and updated the files.  

Please let me know in case you have further issues.

Thanks,
Veer

**Comment by aitorarrietamarcos** [comment]
> Hi Aitor,
> 
> Thanks for your feedback. I have added the Aerospace Blockset and Aerospace Toolbox in the README.md file. Please note that the Aerospace Blockset and Aerospace Toolbox are only required for the "purePursuitUSCity" model to convert from rad/s to degree/s. In case of the absence of these two toolboxes, define the conversion factor from rad/s to degree/s using a gain block and use the model.
> 
> Regarding the packEgo function error, as mentioned by Mustafa, there was an issue with the Scenario Reader block. The scenario scene was located in my local folder. I have fixed the issue and updated the files.
> 
> Please let me know in case you have further issues.
> 
> Thanks,
> Veer

Thanks Veer!

Both are minnor things. Very good job in any case, I think I will use the model for teaching in an undergrad course.

Best regards,

Aitor

**Comment by veeralakshendra** [comment]
Sure, please continue providing feedback.

Regards,
Veer
